"""rename address

Revision ID: fd2cb1dca998
Revises: d9f72b1a26ff
Create Date: 2025-03-27 11:09:30.315240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd2cb1dca998'
down_revision = 'd9f72b1a26ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name='address')


    # ### end Alembic commands ###
